version: '3.8'

services:
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - rhymes-api
  rhymes-api:
    build:
      context: ./services/rhymes-api
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - rhymes-db
  rhymes-db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod: