apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rhymes-api
  name: rhymes-api
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: rhymes-api
status:
  loadBalancer: {}
